# Generated by Django 5.2 on 2025-05-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_manga_category_merch_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='category',
            field=models.CharField(choices=[('Action and Heroism', 'Action and Heroism'), ('Shonen (少年) Manga', 'Shonen (少年) Manga'), ('Shojo (少女) Manga', 'Shojo (少女) Manga'), ('Seinen (青年) Manga', 'Seinen (青年) Manga'), ('Josei (女性) Manga', 'Josei (女性) Manga'), ('Fantasy and Adventure', 'Fantasy and Adventure'), ('Kawaii', 'Kawaii')], default='Shonen (少年) Manga', max_length=50),
        ),
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Stationery', 'Stationery'), ('Accessories', 'Accessories'), ('Clothes', 'Clothes'), ('Posters & Wall Art', 'Posters & Wall Art'), ('Figures & Statues', 'Figures & Statues')], default='Clothes', max_length=50),
        ),
        migrations.DeleteModel(
            name='Manga_Category',
        ),
        migrations.DeleteModel(
            name='Merch_Category',
        ),
    ]
