# Generated by Django 5.2 on 2025-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='volume',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='writer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
