# Generated by Django 5.2 on 2025-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_manga_volume_manga_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
